# site stuff
title: eluum blog
email: eluum-contact@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  A small blog for a few things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# theme
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
